package com.example.gamelistpibien.model.enums;

public enum Tag {
    //ACCIÓN
    ACTION, FIGHTING, BEATEMUP, HACKNSLASH, ARCADE, PLATFORM,
    //TIROS
    SHOOTER,
    //ESTRATEGIA
    STRATEGY, RTS, TBS, MOBA, TOWERDEFENSE,
    //AVENTURA
    ADVENTURE, VISUALNOVEL, GRAPHICADV, SURVIVAL, HORROR, STEALTH, BATTLEROYALE,
    //ROL
    RPG, MMORPG, ROGUELIKE,
    //OTROS
    SIMULATION, SPORT, RACING, FIRSTPERSON, THIRDPERSON, SANDBOX, MUSICAL, PUZZLE, PARTY, EDUCATIVE, INDIE, ONLINE, SINGLEPLAYER, MULTIPLAYER
}
